name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "18"
          - "20"
          - "22"

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: eslint-github-pr-check
        uses: ./
        with:
          tool_name: eslint-github-pr-check
          reporter: github-pr-check
          level: info
          eslint_flags: "testdata/ --ignore-pattern /test-subproject/"
      - name: eslint-github-check
        uses: ./
        with:
          tool_name: eslint-github-check
          reporter: github-check
          level: warning
          eslint_flags: "testdata/ --ignore-pattern /test-subproject/"
      - name: eslint-github-pr-review
        uses: ./
        with:
          tool_name: eslint-github-pr-review
          reporter: github-pr-review
          eslint_flags: "testdata/ --ignore-pattern /test-subproject/"
      - name: eslint-subproject-github-pr-review
        uses: ./
        with:
          tool_name: eslint-subproject-github-pr-review
          reporter: github-pr-review
          workdir: ./test-subproject
          eslint_flags: "sub-testdata/"
      - name: eslint-subproject
        uses: ./
        with:
          tool_name: eslint-subproject
          workdir: ./test-subproject
          eslint_flags: "sub-testdata/"
          reporter: github-check
          level: warning
          filter_mode: file
      - name: eslint-only-changed
        uses: ./
        with:
          tool_name: eslint-only-changed
          reporter: github-check
          level: warning
          only_changed: true
          eslint_flags: "testdata/ --ignore-pattern /test-subproject/"
      - name: eslint-subproject-only-changed
        uses: ./
        with:
          tool_name: eslint-subproject-only-changed
          workdir: ./test-subproject
          reporter: github-check
          level: warning
          filter_mode: file
          only_changed: true
          eslint_flags: "sub-testdata/"
