name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          cache: "npm"
      - run: npm ci
      - name: Test eslint-formatter-rdjson
        run: ./eslint-formatter-rdjson/test.sh
      - name: Test eslint_flags parsing
        run: ./script_test.sh
